
# KKKKKKKKK    KKKKKKK  iiii          tttt
# K:::::::K    K:::::K i::::i      ttt:::t
# K:::::::K    K:::::K  iiii       t:::::t
# K:::::::K   K::::::K             t:::::t
# KK::::::K  K:::::KKKiiiiiiittttttt:::::ttttttt        ssssssssss
# K:::::K K:::::K   i:::::it:::::::::::::::::t      ss::::::::::s
# K::::::K:::::K     i::::it:::::::::::::::::t    ss:::::::::::::s
# K:::::::::::K      i::::itttttt:::::::tttttt    s::::::ssss:::::s
# K:::::::::::K      i::::i      t:::::t           s:::::s  ssssss
# K::::::K:::::K     i::::i      t:::::t             s::::::s
# K:::::K K:::::K    i::::i      t:::::t                s::::::s
# KK::::::K  K:::::KKK i::::i      t:::::t    ttttttssssss   s:::::s
# K:::::::K   K::::::Ki::::::i     t::::::tttt:::::ts:::::ssss::::::s
# K:::::::K    K:::::Ki::::::i     tt::::::::::::::ts::::::::::::::s
# K:::::::K    K:::::Ki::::::i       tt:::::::::::tt s:::::::::::ss
# KKKKKKKKK    KKKKKKKiiiiiiii         ttttttttttt    sssssssssss
#-------------------------------------------------------------------#
#  ·▄▄▄      ▄▄▄       ▄▄·       ▄▄▄  ▄▄▄▄▄▄▄▄ .▐▄• ▄
#  ▐▄▄·▪     ▀▄ █·    ▐█ ▌▪▪     ▀▄ █·•██  ▀▄.▀· █▌█▌▪
#  ██▪  ▄█▀▄ ▐▀▀▄     ██ ▄▄ ▄█▀▄ ▐▀▀▄  ▐█.▪▐▀▀▪▄ ·██·
#  ██▌.▐█▌.▐▌▐█•█▌    ▐███▌▐█▌.▐▌▐█•█▌ ▐█▌·▐█▄▄▌▪▐█·█▌
#  ▀▀▀  ▀█▄▀▪.▀  ▀    ·▀▀▀  ▀█▄▀▪.▀  ▀ ▀▀▀  ▀▀▀ •▀▀ ▀▀
#-------------------------------------------------------------------#

Prefix: '&7[&3&lCortex&7]'