name: CortexKits
version: 1.0-SNAPSHOT
main: me.coolmike35.cortexkits.CortexKits
api-version: 1.13
depend: [ HempCore ]
description: A kit plugin for the Cortex Network
authors: [ Hempfest, Coolmike35 ]
